monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/dev.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        Master:
            type: stream
            path: "%kernel.logs_dir%/log.info"
            level: info
            channels: app